### GENERAL SETTINGS ###

# Site settings
title: Autamus Docker Library
description: "Library of Singularity containers for HPC"
baseurl: "/registry" #important: start with /
url: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more-->

colors:  #in hex code if not noted else
  primary: "#31363C"
  primary_rgb: "49,54,60" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#709EE4"
  link: "#31363C"
  link_hover: "#709EE4"
  footer_heading: "#777"
  footer_content: "#31363C"

# Making projects separate from posts
collections:
  library:
    output: true
    permalink: /r/:title/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
github: https://github.com/autamus
repo: https://github.com/autamus/registry
docs: https://autamus.io/docs/
maintainer: "@autamus"
maintainer_url: https://github.com/autamus

about: "Autamus is a Semi-Autonomous Build System for Scientific Containers."
