spack:
  view: true
  packages:
    all:
      target: [x86_64_v3, aarch64]
  config:
    concretizer: clingo
    compiler:
      target: [x86_64_v3, aarch64]
    install_missing_compilers: true
  container:
    strip: true
    os_packages:
      build:
        - python3-boto3
        - python3-dev
  mirrors:
    autamus: s3://autamus-cache
