spack:
  view: true
  packages:
    all:
      target: [x86_64]
  config:
    compiler:
      target: x86_64
    concretizer: clingo
    install_missing_compilers: true
  container:
    strip: true
    os_packages:
      build:
        - python3-boto3
  mirrors:
    autamus: s3://autamus-cache