name: "Automatic Binoc Scan"

on:
  schedule:
    - cron: '0 14 * * *'
    
jobs:
  auto-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Run Binoc Scan
        uses: autamus/binoc@main
        with:
          git_token: ${{ secrets.BINOC_GIT_TOKEN }}
          git_username: ${{ secrets.BINOC_GIT_USERNAME }}
          git_email: ${{ secrets.BINOC_GIT_EMAIL }}
          git_name: ${{ secrets.BINOC_GIT_NAME }}
          general_action: 'true'
          repo_spackupstreamlink: 'https://raw.githubusercontent.com/spack/spack/develop/var/spack/repos/builtin/packages/{{package}}/package.py'
